# Generated by Django 5.0.7 on 2024-07-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thermohygrometer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100)),
                ('pn', models.CharField(max_length=100)),
                ('sn', models.CharField(max_length=100)),
                ('instrument_name', models.CharField(max_length=100)),
                ('sensor_sn', models.CharField(blank=True, max_length=100, null=True)),
                ('sensor_pn', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
