# Generated by Django 5.0.7 on 2024-08-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluke_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermohygrometermodel',
            name='last_connection_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
