# Generated by Django 5.0.7 on 2024-07-30 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluke_data', '0002_measuresmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measuresmodel',
            name='pn_sn',
        ),
        migrations.AddField(
            model_name='measuresmodel',
            name='instrument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fluke_data.thermohygrometermodel'),
        ),
        migrations.AddField(
            model_name='measuresmodel',
            name='pn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='measuresmodel',
            name='sn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
