# Generated by Django 5.0.7 on 2024-09-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluke_data', '0003_calibrationcertificatemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermohygrometermodel',
            name='time_interval_to_save_measures',
            field=models.IntegerField(default=5, help_text='Interval in minutes to save measures'),
        ),
    ]
