# Generated by Django 5.0.7 on 2024-08-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluke_data', '0003_remove_measuresmodel_pn_sn_measuresmodel_instrument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermohygrometermodel',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
