# Generated by Django 5.0.7 on 2024-09-05 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluke_data', '0004_thermohygrometermodel_time_interval_to_save_measures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationcertificatemodel',
            name='instrument',
        ),
        migrations.AddField(
            model_name='thermohygrometermodel',
            name='calibration_certificate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fluke_data.calibrationcertificatemodel'),
        ),
    ]
