# Generated by Django 5.0.7 on 2024-08-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluke_data', '0004_thermohygrometermodel_is_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuresmodel',
            name='sensor_pn',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='measuresmodel',
            name='sensor_sn',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='measuresmodel',
            name='date',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='measuresmodel',
            name='humidity',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='measuresmodel',
            name='pn',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='measuresmodel',
            name='sn',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='measuresmodel',
            name='temperature',
            field=models.FloatField(editable=False),
        ),
    ]
