# Generated by Django 5.0.7 on 2024-08-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluke_data', '0005_measuresmodel_sensor_pn_measuresmodel_sensor_sn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermohygrometermodel',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
