# Generated by Django 5.0.7 on 2024-09-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluke_data', '0006_alter_thermohygrometermodel_time_interval_to_save_measures'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuresmodel',
            name='corrected_humidity',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='measuresmodel',
            name='corrected_temperature',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
